# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.setEnabled(True)
        Main.resize(1161, 806)
        Main.setMinimumSize(QtCore.QSize(1161, 806))
        Main.setMaximumSize(QtCore.QSize(1161, 806))
        Main.setBaseSize(QtCore.QSize(1161, 681))
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(280, 750, 211, 51))
        self.startButton.setObjectName("startButton")
        self.popTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.popTextEdit.setGeometry(QtCore.QRect(20, 40, 241, 41))
        self.popTextEdit.setObjectName("popTextEdit")
        self.daysTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.daysTextEdit.setGeometry(QtCore.QRect(20, 130, 241, 41))
        self.daysTextEdit.setObjectName("daysTextEdit")
        self.stimeTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stimeTextEdit.setGeometry(QtCore.QRect(20, 220, 241, 41))
        self.stimeTextEdit.setObjectName("stimeTextEdit")
        self.norTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.norTextEdit.setGeometry(QtCore.QRect(20, 310, 241, 41))
        self.norTextEdit.setObjectName("norTextEdit")
        self.popLabel = QtWidgets.QLabel(self.centralwidget)
        self.popLabel.setGeometry(QtCore.QRect(20, 10, 421, 21))
        self.popLabel.setObjectName("popLabel")
        self.daysLabel = QtWidgets.QLabel(self.centralwidget)
        self.daysLabel.setGeometry(QtCore.QRect(20, 100, 421, 21))
        self.daysLabel.setObjectName("daysLabel")
        self.itimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.itimeLabel.setGeometry(QtCore.QRect(20, 190, 421, 21))
        self.itimeLabel.setObjectName("itimeLabel")
        self.norLabel = QtWidgets.QLabel(self.centralwidget)
        self.norLabel.setGeometry(QtCore.QRect(20, 280, 421, 21))
        self.norLabel.setObjectName("norLabel")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setEnabled(True)
        self.loadButton.setGeometry(QtCore.QRect(500, 750, 211, 51))
        self.loadButton.setObjectName("loadButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setGeometry(QtCore.QRect(720, 750, 211, 51))
        self.saveButton.setObjectName("saveButton")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(280, 10, 871, 731))
        self.outputLabel.setText("")
        self.outputLabel.setPixmap(QtGui.QPixmap("__pictures__/blank.png"))
        self.outputLabel.setScaledContents(True)
        self.outputLabel.setObjectName("outputLabel")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(30, 730, 211, 71))
        self.errorLabel.setObjectName("errorLabel")
        self.rosTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.rosTextEdit.setGeometry(QtCore.QRect(20, 400, 241, 41))
        self.rosTextEdit.setObjectName("rosTextEdit")
        self.rosLabel = QtWidgets.QLabel(self.centralwidget)
        self.rosLabel.setGeometry(QtCore.QRect(20, 370, 421, 21))
        self.rosLabel.setObjectName("rosLabel")
        self.weatherTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.weatherTextEdit.setGeometry(QtCore.QRect(20, 490, 241, 41))
        self.weatherTextEdit.setObjectName("weatherTextEdit")
        self.weatherLabel = QtWidgets.QLabel(self.centralwidget)
        self.weatherLabel.setGeometry(QtCore.QRect(20, 460, 421, 21))
        self.weatherLabel.setObjectName("weatherLabel")
        self.capacityTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.capacityTextEdit.setGeometry(QtCore.QRect(20, 580, 241, 41))
        self.capacityTextEdit.setObjectName("capacityTextEdit")
        self.capacityLabel = QtWidgets.QLabel(self.centralwidget)
        self.capacityLabel.setGeometry(QtCore.QRect(20, 550, 421, 21))
        self.capacityLabel.setObjectName("capacityLabel")
        self.urateTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.urateTextEdit.setGeometry(QtCore.QRect(20, 670, 241, 41))
        self.urateTextEdit.setObjectName("urateTextEdit")
        self.urateLabel = QtWidgets.QLabel(self.centralwidget)
        self.urateLabel.setGeometry(QtCore.QRect(20, 640, 421, 21))
        self.urateLabel.setObjectName("urateLabel")
        self.advancedButton = QtWidgets.QPushButton(self.centralwidget)
        self.advancedButton.setEnabled(True)
        self.advancedButton.setGeometry(QtCore.QRect(940, 750, 211, 51))
        self.advancedButton.setObjectName("advancedButton")
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Coronavirus Minority Game"))
        self.startButton.setText(_translate("Main", "Start"))
        self.popTextEdit.setPlaceholderText(_translate("Main", "Integer greater than 10"))
        self.daysTextEdit.setPlaceholderText(_translate("Main", "Integer greater than 0"))
        self.stimeTextEdit.setPlaceholderText(_translate("Main", "Integer greater than 0"))
        self.norTextEdit.setPlaceholderText(_translate("Main", "Integer greater than 0"))
        self.popLabel.setText(_translate("Main", "Population Size:"))
        self.daysLabel.setText(_translate("Main", "Number of Days:"))
        self.itimeLabel.setText(_translate("Main", "Sick Time:"))
        self.norLabel.setText(_translate("Main", "Number of Restaurants:"))
        self.loadButton.setText(_translate("Main", "Load"))
        self.saveButton.setText(_translate("Main", "Save"))
        self.errorLabel.setText(_translate("Main", "No Errors\n"
"Currently Present"))
        self.rosTextEdit.setPlaceholderText(_translate("Main", "Number between 0-3.5"))
        self.rosLabel.setText(_translate("Main", "Rate of Spread:"))
        self.weatherTextEdit.setPlaceholderText(_translate("Main", "Number greater than 0"))
        self.weatherLabel.setText(_translate("Main", "Weather Condition:"))
        self.capacityTextEdit.setPlaceholderText(_translate("Main", "Integer greater than 0"))
        self.capacityLabel.setText(_translate("Main", "Restaurant Capacity:"))
        self.urateTextEdit.setPlaceholderText(_translate("Main", "Number between 0-1"))
        self.urateLabel.setText(_translate("Main", "Unemployment Rate"))
        self.advancedButton.setText(_translate("Main", "Advanced Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())

